In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.mixture import GaussianMixture

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('segmentation_df.csv')
df.head()

,household_key,total_sales_x,avg_sales,total_quantity,avg_quantity,avg_basket_size,total_orders,unique_visits_days,order_frequency,relative_recency,avg_days_between_visits,coupon_dependecy_ratio
0,1,4330.16,2.507331,1997,1.156340,23.220930,86,79,7.616279,6,8.397436,0.072399
1,2,1954.34,2.737171,834,1.168067,18.533333,45,45,12.555556,44,12.840909,0.010623
2,3,2653.21,2.877668,8540,9.262473,181.702128,47,46,12.553191,9,13.111111,0.071909
3,4,1200.11,3.987076,382,1.269103,12.733333,30,30,17.433333,85,18.034483,0.010416
4,5,779.06,3.509279,245,1.103604,6.125000,40,33,15.450000,9,19.312500,0.000000

In [4]:
df2 = df.drop(columns = ['household_key', 'total_quantity', 'avg_quantity', 'avg_basket_size', 'unique_visits_days','coupon_dependecy_ratio'], axis = 1)
df2.head()

,total_sales_x,avg_sales,total_orders,order_frequency,relative_recency,avg_days_between_visits
0,4330.16,2.507331,86,7.616279,6,8.397436
1,1954.34,2.737171,45,12.555556,44,12.840909
2,2653.21,2.877668,47,12.553191,9,13.111111
3,1200.11,3.987076,30,17.433333,85,18.034483
4,779.06,3.509279,40,15.450000,9,19.312500

In [5]:
scaler = StandardScaler()
df2 = pd.DataFrame(scaler.fit_transform(df2), columns = df2.columns)
df2.head()

,total_sales_x,avg_sales,total_orders,order_frequency,relative_recency,avg_days_between_visits
0,0.330662,-0.642824,-0.212662,-0.342215,-0.327726,-0.310312
1,-0.378886,-0.410892,-0.567192,-0.071914,0.277581,-0.150210
2,-0.170166,-0.269116,-0.549898,-0.072043,-0.279938,-0.140474
3,-0.604140,0.850390,-0.696898,0.195021,0.930675,0.036920
4,-0.729888,0.368244,-0.610427,0.086484,-0.279938,0.082968

In [10]:
pca = PCA(n_components = 6)
principal_components = pca.fit_transform(df2)
principal_components

array([[-0.47842288, -0.5666783 , -0.31911823, -0.08900771,  0.47738021,
        -0.03050527],
       [ 0.38162161, -0.70769202,  0.17894512,  0.15003155,  0.19348649,
         0.02116545],
       [ 0.13330098, -0.52613229,  0.04091149, -0.35048709,  0.29636863,
         0.01105318],
       ...,
       [-0.79772269, -0.3467901 , -0.01436321, -0.15923316, -0.484587  ,
        -0.0698638 ],
       [-0.40638243, -0.43757112,  0.00813268, -0.27971739,  0.18988669,
        -0.05283029],
       [-0.83671594,  0.36875554,  0.36386161, -0.29335482,  0.37664168,
        -0.05292342]], shape=(2500, 6))

In [11]:
eigen_values = pca.explained_variance_
eigen_values

array([2.75299206, 1.14924577, 0.92840234, 0.84625586, 0.27847799,
       0.04702694])

In [12]:
pca.explained_variance_ratio_

array([0.45864848, 0.19146434, 0.15467183, 0.14098623, 0.04639443,
       0.00783469])

In [13]:
cumulative_var = np.cumsum(eigen_values)
cumulative_var

array([2.75299206, 3.90223783, 4.83064017, 5.67689602, 5.95537402,
       6.00240096])

- Using only the RFM matrix, the explained variance comes out nearly 59% which is low than the minimum ideal variance (70% to 90%)