In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.mixture import GaussianMixture

import warnings
warnings.filterwarnings('ignore')

In [2]:
df2 = pd.read_csv('merged_transactions_product.csv')
df2.head()

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC,MANUFACTURER,DEPARTMENT,BRAND,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,0.0,0.0,69,PRODUCE,Private,POTATOES,POTATOES RUSSET (BULK&BAG),5 LB
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,0.0,0.0,2,PRODUCE,National,ONIONS,ONIONS SWEET (BULK&BAG),40 LB
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,0.0,0.0,69,PRODUCE,Private,VEGETABLES - ALL OTHERS,CELERY,
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,0.0,0.0,2,PRODUCE,National,TROPICAL FRUIT,BANANAS,40 LB
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,0.0,0.0,69,PRODUCE,Private,ORGANICS FRUIT & VEGETABLES,ORGANIC CARROTS,1 LB

In [3]:
df2.drop(columns=['STORE_ID','CURR_SIZE_OF_PRODUCT','SUB_COMMODITY_DESC'],inplace=True)

In [4]:
df2['BRAND'].value_counts()

BRAND
National    1849560
Private      746172
Name: count, dtype: int64

In [5]:
df2.drop(columns = ['BRAND'],inplace=True)

In [6]:
df2.head()

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC,MANUFACTURER,DEPARTMENT,COMMODITY_DESC
0,2375,26984851472,1,1004906,1,1.39,-0.60,1631,1,0.0,0.0,69,PRODUCE,POTATOES
1,2375,26984851472,1,1033142,1,0.82,0.00,1631,1,0.0,0.0,2,PRODUCE,ONIONS
2,2375,26984851472,1,1036325,1,0.99,-0.30,1631,1,0.0,0.0,69,PRODUCE,VEGETABLES - ALL OTHERS
3,2375,26984851472,1,1082185,1,1.21,0.00,1631,1,0.0,0.0,2,PRODUCE,TROPICAL FRUIT
4,2375,26984851472,1,8160430,1,1.50,-0.39,1631,1,0.0,0.0,69,PRODUCE,ORGANICS FRUIT & VEGETABLES

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2595732 entries, 0 to 2595731
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   household_key      int64
 1   BASKET_ID          int64
 2   DAY                int64
 3   PRODUCT_ID         int64
 4   QUANTITY           int64
 5   SALES_VALUE        float64
 6   RETAIL_DISC        float64
 7   TRANS_TIME         int64
 8   WEEK_NO            int64
 9   COUPON_DISC        float64
 10  COUPON_MATCH_DISC  float64
 11  MANUFACTURER       int64
 12  DEPARTMENT         object
 13  COMMODITY_DESC     object
dtypes: float64(4), int64(8), object(2)
memory usage: 277.3+ MB

In [8]:
df2['MANUFACTURER'].value_counts()

MANUFACTURER
69      731939
2       170773
544      46112
317      39345
103      37895
         ...
5806         1
1460         1
6451         1
3961         1
2191         1
Name: count, Length: 6476, dtype: int64

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2595732 entries, 0 to 2595731
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   household_key      int64
 1   BASKET_ID          int64
 2   DAY                int64
 3   PRODUCT_ID         int64
 4   QUANTITY           int64
 5   SALES_VALUE        float64
 6   RETAIL_DISC        float64
 7   TRANS_TIME         int64
 8   WEEK_NO            int64
 9   COUPON_DISC        float64
 10  COUPON_MATCH_DISC  float64
 11  MANUFACTURER       int64
 12  DEPARTMENT         object
 13  COMMODITY_DESC     object
dtypes: float64(4), int64(8), object(2)
memory usage: 277.3+ MB

**CHECKING FOR SPACES IN COLUMNS**

In [10]:
product = pd.read_csv('../dunnhumby_The-Complete-Journey/product.csv')

In [11]:
product[product['PRODUCT_ID'] == 5978656]

,PRODUCT_ID,MANUFACTURER,DEPARTMENT,BRAND,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT
55057,5978656,1,,National,,,

In [12]:
product[product['PRODUCT_ID'] == 5978656]['SUB_COMMODITY_DESC']

55057
Name: SUB_COMMODITY_DESC, dtype: object

In [13]:
product.isnull().sum()

PRODUCT_ID              0
MANUFACTURER            0
DEPARTMENT              0
BRAND                   0
COMMODITY_DESC          0
SUB_COMMODITY_DESC      0
CURR_SIZE_OF_PRODUCT    0
dtype: int64

In [14]:
df2[df2['PRODUCT_ID'] == 5978656]

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC,MANUFACTURER,DEPARTMENT,COMMODITY_DESC
249,2305,26996870743,2,5978656,0,0.0,0.0,1300,1,-1.00,0.0,1,,
293,271,26997082949,2,5978656,0,0.0,0.0,1719,1,-2.00,0.0,1,,
2143,907,27045792138,6,5978656,0,0.0,0.0,1641,2,-2.19,0.0,1,,
2412,1828,27057550740,7,5978656,0,0.0,0.0,1335,2,-0.30,0.0,1,,
2801,575,27069463088,8,5978656,0,0.0,0.0,2209,2,-0.30,0.0,1,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2594232,104,42289786425,711,5978656,0,0.0,0.0,1304,102,-1.00,0.0,1,,
2594374,1856,42289801862,711,5978656,0,0.0,0.0,1613,102,-1.00,0.0,1,,
2594684,1717,42289836889,711,5978656,0,0.0,0.0,1734,102,-1.75,0.0,1,,
2595280,2338,42289891597,711,5978656,0,0.0,0.0,1258,102,-1.00,0.0,1,,
2595589,303,42289918892,711,5978656,0,0.0,0.0,1513,102,-1.00,0.0,1,,

In [15]:
df2.isnull().sum()

household_key        0
BASKET_ID            0
DAY                  0
PRODUCT_ID           0
QUANTITY             0
SALES_VALUE          0
RETAIL_DISC          0
TRANS_TIME           0
WEEK_NO              0
COUPON_DISC          0
COUPON_MATCH_DISC    0
MANUFACTURER         0
DEPARTMENT           0
COMMODITY_DESC       0
dtype: int64

In [16]:
df2.duplicated().sum()

np.int64(0)

In [17]:
product.head()

,PRODUCT_ID,MANUFACTURER,DEPARTMENT,BRAND,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT
0,25671,2,GROCERY,National,FRZN ICE,ICE - CRUSHED/CUBED,22 LB
1,26081,2,MISC. TRANS.,National,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION,
2,26093,69,PASTRY,Private,BREAD,BREAD:ITALIAN/FRENCH,
3,26190,69,GROCERY,Private,FRUIT - SHELF STABLE,APPLE SAUCE,50 OZ
4,26355,69,GROCERY,Private,COOKIES/CONES,SPECIALTY COOKIES,14 OZ

In [18]:
product_cleaned = product.replace(r'^\s*$', np.nan, regex=True)

In [19]:
product_cleaned.isnull().sum()

PRODUCT_ID                  0
MANUFACTURER                0
DEPARTMENT                 15
BRAND                       0
COMMODITY_DESC             15
SUB_COMMODITY_DESC         15
CURR_SIZE_OF_PRODUCT    30607
dtype: int64

In [20]:
product_cleaned[product_cleaned['PRODUCT_ID'] == 5978656]['SUB_COMMODITY_DESC']

55057    NaN
Name: SUB_COMMODITY_DESC, dtype: object

In [21]:
df2 = df2.replace(r'^\s*$', np.nan, regex=True)

df2.isnull().sum()

household_key           0
BASKET_ID               0
DAY                     0
PRODUCT_ID              0
QUANTITY                0
SALES_VALUE             0
RETAIL_DISC             0
TRANS_TIME              0
WEEK_NO                 0
COUPON_DISC             0
COUPON_MATCH_DISC       0
MANUFACTURER            0
DEPARTMENT           7839
COMMODITY_DESC       7839
dtype: int64

In [22]:
df2.shape

(2595732, 14)

In [23]:
df2['DEPARTMENT'].value_counts()

DEPARTMENT
GROCERY            1646076
DRUG GM             277232
PRODUCE             257290
MEAT-PCKGD          111957
MEAT                 88416
DELI                 62787
PASTRY               38179
NUTRITION            32164
KIOSK-GAS            22059
SEAFOOD-PCKGD        11216
SALAD BAR             9516
COSMETICS             7692
MISC SALES TRAN       6050
FLORAL                4524
SEAFOOD               4093
MISC. TRANS.          2351
SPIRITS               2119
TRAVEL & LEISUR        862
COUP/STR & MFG         817
CHEF SHOPPE            766
GARDEN CENTER          720
RESTAURANT             465
FROZEN GROCERY         251
AUTOMOTIVE              65
DAIRY DELI              53
GM MERCH EXP            49
CNTRL/STORE SUP         21
POSTAL CENTER           20
PHOTO                   17
RX                      14
DELI/SNACK BAR          11
PHARMACY SUPPLY          6
MEAT-WHSE                6
VIDEO RENTAL             5
TOYS                     5
PROD-WHS SALES           4
HBC                      4
VIDEO                    3
PORK                     2
GRO BAKERY               2
CHARITABLE CONT          2
HOUSEWARES               1
ELECT &PLUMBING          1
Name: count, dtype: int64

In [24]:
df2 = df2.fillna('Unknown')

In [25]:
df2.isnull().sum()

household_key        0
BASKET_ID            0
DAY                  0
PRODUCT_ID           0
QUANTITY             0
SALES_VALUE          0
RETAIL_DISC          0
TRANS_TIME           0
WEEK_NO              0
COUPON_DISC          0
COUPON_MATCH_DISC    0
MANUFACTURER         0
DEPARTMENT           0
COMMODITY_DESC       0
dtype: int64

#### FEATURES TO BE CREATED

1. Features related to spending - sales_value,quantity
2. Features related to frequency - Basket_Id
3. Features related to recency - Day
4. Features related to discount - Coupon_disc...

In [26]:
customer_spending = df2.groupby('household_key').agg({
    'SALES_VALUE':['sum','mean','min','max'],
    'QUANTITY':['sum','mean','min','max'],
})

In [27]:
customer_spending.head()

              SALES_VALUE                        QUANTITY
                      sum      mean   min    max      sum      mean min   max
household_key
1                 4330.16  2.507331  0.00  12.50     1997  1.156340   0     6
2                 1954.34  2.737171  0.00  21.99      834  1.168067   0     5
3                 2653.21  2.877668  0.00  29.37     8540  9.262473   0  6949
4                 1200.11  3.987076  0.00  37.34      382  1.269103   0     6
5                  779.06  3.509279  0.34  21.99      245  1.103604   1     4

In [28]:
customer_spending.columns = ['total_sales','avg_sales','min_sales','max_sales','total_quantity','avg_quantity','min_quantity','max_quantity']

customer_spending.head()

,total_sales,avg_sales,min_sales,max_sales,total_quantity,avg_quantity,min_quantity,max_quantity
household_key,,,,,,,,
1,4330.16,2.507331,0.00,12.50,1997,1.156340,0,6
2,1954.34,2.737171,0.00,21.99,834,1.168067,0,5
3,2653.21,2.877668,0.00,29.37,8540,9.262473,0,6949
4,1200.11,3.987076,0.00,37.34,382,1.269103,0,6
5,779.06,3.509279,0.34,21.99,245,1.103604,1,4

In [29]:
customer_spending.reset_index(inplace=True)

In [31]:
customer_spending.head()

,household_key,total_sales,avg_sales,min_sales,max_sales,total_quantity,avg_quantity,min_quantity,max_quantity
0,1,4330.16,2.507331,0.00,12.50,1997,1.156340,0,6
1,2,1954.34,2.737171,0.00,21.99,834,1.168067,0,5
2,3,2653.21,2.877668,0.00,29.37,8540,9.262473,0,6949
3,4,1200.11,3.987076,0.00,37.34,382,1.269103,0,6
4,5,779.06,3.509279,0.34,21.99,245,1.103604,1,4

**FREQUENCY FEATURES**

In [32]:
frequency_features = df2.groupby('household_key').agg({
    'BASKET_ID': ['nunique'],
    'DAY': ['nunique', 'min','max']
})

In [33]:
frequency_features.columns = ['total_visits','unique_visits_days','first_purchase','last_purchase']

In [34]:
frequency_features.reset_index(inplace=True)

In [35]:
frequency_features.head()

,household_key,total_visits,unique_visits_days,first_purchase,last_purchase
0,1,86,79,51,706
1,2,45,45,103,668
2,3,47,46,113,703
3,4,30,30,104,627
4,5,40,33,85,703

In [36]:
frequency_features['active_window'] =  (frequency_features['last_purchase'] - frequency_features['first_purchase'])

frequency_features['order_frequency'] = (frequency_features['active_window'] / frequency_features['total_visits'])

In [37]:
customer_spending['avg_basket_size'] = customer_spending['total_quantity'] / frequency_features['total_visits']

In [38]:
frequency_features.columns = ['household_key', 'total_orders','unique_visits_days','first_purchase','last_purchase', 'active_window', 'order_frequency']

In [39]:
frequency_features.head()

,household_key,total_orders,unique_visits_days,first_purchase,last_purchase,active_window,order_frequency
0,1,86,79,51,706,655,7.616279
1,2,45,45,103,668,565,12.555556
2,3,47,46,113,703,590,12.553191
3,4,30,30,104,627,523,17.433333
4,5,40,33,85,703,618,15.450000

_Note on Chatrapal's idea_

**RECENCY FEATURES**

In [40]:
# unique baskets per household
visits = df2.drop_duplicates(subset=['household_key', 'BASKET_ID'])[['household_key', 'BASKET_ID', 'DAY']]

# unique days per household
visit_days = visits.drop_duplicates(subset=['household_key', 'DAY'])[['household_key', 'DAY']]

# avg days between visits
recency_features = (visit_days.groupby('household_key')['DAY'].apply(lambda x: x.sort_values().diff().mean()).reset_index())
recency_features.columns = ['household_key', 'avg_days_between_visits']

# relative recency (last day of study is 712)
relative_recency = visit_days.groupby('household_key')['DAY'].agg(first_day='min', last_day='max').reset_index()
relative_recency['active_window'] = (relative_recency['last_day'] - relative_recency['first_day'])
relative_recency['relative_recency'] = (712 - relative_recency['last_day']).replace(0, 1)

relative_recency_clean = relative_recency[['household_key', 'relative_recency']]

In [41]:
relative_recency.head()

   household_key  first_day  last_day  active_window  relative_recency
0              1         51       706            655                 6
1              2        103       668            565                44
2              3        113       703            590                 9
3              4        104       627            523                85
4              5         85       703            618                 9

In [42]:
recency_features.head()

   household_key  avg_days_between_visits
0              1                 8.397436
1              2                12.840909
2              3                13.111111
3              4                18.034483
4              5                19.312500

**DISCOUNT FEATURES**

In [43]:
df2.head(
    
)

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC,MANUFACTURER,DEPARTMENT,COMMODITY_DESC
0,2375,26984851472,1,1004906,1,1.39,-0.60,1631,1,0.0,0.0,69,PRODUCE,POTATOES
1,2375,26984851472,1,1033142,1,0.82,0.00,1631,1,0.0,0.0,2,PRODUCE,ONIONS
2,2375,26984851472,1,1036325,1,0.99,-0.30,1631,1,0.0,0.0,69,PRODUCE,VEGETABLES - ALL OTHERS
3,2375,26984851472,1,1082185,1,1.21,0.00,1631,1,0.0,0.0,2,PRODUCE,TROPICAL FRUIT
4,2375,26984851472,1,8160430,1,1.50,-0.39,1631,1,0.0,0.0,69,PRODUCE,ORGANICS FRUIT & VEGETABLES

In [44]:
disc_features=[]
discount_features = pd.DataFrame()

total_sales = df2.groupby('household_key').agg({
    'SALES_VALUE': ['sum']
})

coupon_dependent_sales = df2[df2['COUPON_DISC'] != 0].groupby('household_key').agg({
    'SALES_VALUE': ['sum']
})

discount_features = pd.concat([discount_features,total_sales,coupon_dependent_sales], axis=1)
discount_features.columns = ['total_sales','coupon_dependent_sales']
discount_features['coupon_dependecy_ratio'] = discount_features['coupon_dependent_sales'] / discount_features['total_sales']
discount_features.reset_index(inplace=True)
discount_features.fillna(0, inplace=True)
discount_features.head()

   household_key  total_sales  coupon_dependent_sales  coupon_dependecy_ratio
0              1      4330.16                  313.50                0.072399
1              2      1954.34                   20.76                0.010623
2              3      2653.21                  190.79                0.071909
3              4      1200.11                   12.50                0.010416
4              5       779.06                    0.00                0.000000

In [45]:
df2.head()

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC,MANUFACTURER,DEPARTMENT,COMMODITY_DESC
0,2375,26984851472,1,1004906,1,1.39,-0.60,1631,1,0.0,0.0,69,PRODUCE,POTATOES
1,2375,26984851472,1,1033142,1,0.82,0.00,1631,1,0.0,0.0,2,PRODUCE,ONIONS
2,2375,26984851472,1,1036325,1,0.99,-0.30,1631,1,0.0,0.0,69,PRODUCE,VEGETABLES - ALL OTHERS
3,2375,26984851472,1,1082185,1,1.21,0.00,1631,1,0.0,0.0,2,PRODUCE,TROPICAL FRUIT
4,2375,26984851472,1,8160430,1,1.50,-0.39,1631,1,0.0,0.0,69,PRODUCE,ORGANICS FRUIT & VEGETABLES

In [46]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2595732 entries, 0 to 2595731
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   household_key      int64
 1   BASKET_ID          int64
 2   DAY                int64
 3   PRODUCT_ID         int64
 4   QUANTITY           int64
 5   SALES_VALUE        float64
 6   RETAIL_DISC        float64
 7   TRANS_TIME         int64
 8   WEEK_NO            int64
 9   COUPON_DISC        float64
 10  COUPON_MATCH_DISC  float64
 11  MANUFACTURER       int64
 12  DEPARTMENT         object
 13  COMMODITY_DESC     object
dtypes: float64(4), int64(8), object(2)
memory usage: 277.3+ MB

1. customer_spending - household_key	total_sales	   avg_sales    total_quantity	avg_quantity	avg_basket_size

2. frequency_features - household_key	total_orders	unique_visits_days	order_frequency

3. relative_recency - relative_recency

4. recency_features - avg_days_between_visits

5. discount_features - household_key    coupon_dependecy_ratio

In [47]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [48]:
segmentation_df = customer_spending.merge(frequency_features, on='household_key').merge(relative_recency_clean, on='household_key').merge(recency_features, on='household_key').merge(discount_features, on='household_key')
segmentation_df.head()

,household_key,total_sales_x,avg_sales,min_sales,max_sales,total_quantity,avg_quantity,min_quantity,max_quantity,avg_basket_size,total_orders,unique_visits_days,first_purchase,last_purchase,active_window,order_frequency,relative_recency,avg_days_between_visits,total_sales_y,coupon_dependent_sales,coupon_dependecy_ratio
0,1,4330.16,2.507331,0.00,12.50,1997,1.156340,0,6,23.220930,86,79,51,706,655,7.616279,6,8.397436,4330.16,313.50,0.072399
1,2,1954.34,2.737171,0.00,21.99,834,1.168067,0,5,18.533333,45,45,103,668,565,12.555556,44,12.840909,1954.34,20.76,0.010623
2,3,2653.21,2.877668,0.00,29.37,8540,9.262473,0,6949,181.702128,47,46,113,703,590,12.553191,9,13.111111,2653.21,190.79,0.071909
3,4,1200.11,3.987076,0.00,37.34,382,1.269103,0,6,12.733333,30,30,104,627,523,17.433333,85,18.034483,1200.11,12.50,0.010416
4,5,779.06,3.509279,0.34,21.99,245,1.103604,1,4,6.125000,40,33,85,703,618,15.450000,9,19.312500,779.06,0.00,0.000000

In [49]:
segmentation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   household_key            2500 non-null   int64
 1   total_sales_x            2500 non-null   float64
 2   avg_sales                2500 non-null   float64
 3   min_sales                2500 non-null   float64
 4   max_sales                2500 non-null   float64
 5   total_quantity           2500 non-null   int64
 6   avg_quantity             2500 non-null   float64
 7   min_quantity             2500 non-null   int64
 8   max_quantity             2500 non-null   int64
 9   avg_basket_size          2500 non-null   float64
 10  total_orders             2500 non-null   int64
 11  unique_visits_days       2500 non-null   int64
 12  first_purchase           2500 non-null   int64
 13  last_purchase            2500 non-null   int64
 14  active_window            2500 non-null   int64
 15  order_frequency          2500 non-null   float64
 16  relative_recency         2500 non-null   int64
 17  avg_days_between_visits  2497 non-null   float64
 18  total_sales_y            2500 non-null   float64
 19  coupon_dependent_sales   2500 non-null   float64
 20  coupon_dependecy_ratio   2500 non-null   float64
dtypes: float64(11), int64(10)
memory usage: 410.3 KB

In [50]:
segmentation_df.drop(columns=['total_sales_y','min_sales','max_sales','min_quantity','max_quantity','first_purchase','last_purchase','active_window','coupon_dependent_sales'],inplace=True)

In [51]:
segmentation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   household_key            2500 non-null   int64
 1   total_sales_x            2500 non-null   float64
 2   avg_sales                2500 non-null   float64
 3   total_quantity           2500 non-null   int64
 4   avg_quantity             2500 non-null   float64
 5   avg_basket_size          2500 non-null   float64
 6   total_orders             2500 non-null   int64
 7   unique_visits_days       2500 non-null   int64
 8   order_frequency          2500 non-null   float64
 9   relative_recency         2500 non-null   int64
 10  avg_days_between_visits  2497 non-null   float64
 11  coupon_dependecy_ratio   2500 non-null   float64
dtypes: float64(7), int64(5)
memory usage: 234.5 KB

In [52]:
segmentation_df[segmentation_df.isnull().any(axis=1)]

,household_key,total_sales_x,avg_sales,total_quantity,avg_quantity,avg_basket_size,total_orders,unique_visits_days,order_frequency,relative_recency,avg_days_between_visits,coupon_dependecy_ratio
493,494,8.17,2.042500,5,1.250000,5.0,1,1,0.0,618,NaN,0.0
1829,1830,39.44,5.634286,10,1.428571,10.0,1,1,0.0,643,NaN,0.0
1896,1897,19.58,3.916000,5,1.000000,5.0,1,1,0.0,643,NaN,0.0

In [53]:
segmentation_df.fillna(0, inplace=True)

In [54]:
segmentation_df.to_csv('segmentation_df.csv', index=False)